sudo: required
services:
  - docker

before_install:
  - docker build -t ahrav/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ahrav/react-test npm test -- --coverage

after_success:
  - docker build -t ahrav/multi-client ./client
  - docker build -t ahrav/multi-nginx ./nginx
  - docker build -t ahrav/multi-server ./server
  - docker build -t ahrav/multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take images and push to docker hub
  - docker push ahrav/multi-client
  - docker push ahrav/multi-nginx
  - docker push ahrav/multi-server
  - docker push ahrav/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-west-1-083889461427'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
